x-common: &common
  build: docker/
  image: zettascaletech/roscon2024_workshop
  init: true
  stdin_open: true
  tty: true
  environment:
    - DISPLAY=host.docker.internal:0
  volumes:
    - ./zenoh_confs:/ros_ws/zenoh_confs
  expose:
    - "7447/tcp"
    - "7447/udp"
  networks:
    - zenoh-net
  cap_add:
    - NET_ADMIN
  command: bash -c "
    ip link set lo multicast on &&
    tc qdisc add dev eth0 root handle 1: htb default 20 &&
    tc class add dev eth0 parent 1:  classid 1:1  htb rate 150kbit ceil 150kbit &&
    tc class add dev eth0 parent 1:1 classid 1:10 htb rate 30kbit  ceil 30kbit  prio 0 &&
    tc class add dev eth0 parent 1:1 classid 1:20 htb rate 120kbit ceil 150kbit prio 1 &&
    tc filter add dev eth0 parent 1: protocol ip u32 match ip protocol 17 0xff match ip dport 7447 0xffff flowid 1:10 &&
    tc filter add dev eth0 parent 1: protocol ip u32 match ip protocol 17 0xff match ip sport 7447 0xffff flowid 1:10 &&
    exec bash"

services:
  container-a:
    <<: *common
    container_name: container-a
    hostname: container-a

  container-b:
    <<: *common
    container_name: container-b
    hostname: container-b

  container-c:
    <<: *common
    container_name: container-c
    hostname: container-c

networks:
  zenoh-net:
    driver: bridge
